package com.proxyagent.app.nativeagent.quic.crypto

import javax.crypto.Cipher
import javax.crypto.spec.SecretKeySpec

/**
 * QUIC header protection (RFC 9001 §5.4) for the AES-128-based
 * cipher suite. One instance per direction.
 *
 * Header protection encrypts a small set of bits in each packet
 * so an on-path observer can't read the packet number — which
 * would otherwise enable trivial tracking across migrations.
 * The protected portion is:
 *  - **First byte**: low 4 bits for long-header packets, low 5
 *    bits for short-header packets. (The low 2 bits carry the
 *    PN length, the bit above that is "reserved", and on short
 *    headers the next bit up is the key-phase indicator.)
 *  - **Packet number bytes**: all 1-4 of them.
 *
 * The mask is generated by AES-128-ECB encrypting a 16-byte
 * sample of the AEAD ciphertext taken at a fixed position — the
 * sample is always taken from offset `pn_offset + 4`, regardless
 * of the actual PN length. This means even when the PN is
 * shorter than 4 bytes, the sample begins inside the ciphertext.
 *
 * RFC 9001 §5.4.2 defines this fixed-offset sampling so that
 * receivers can take the sample BEFORE they know how long the
 * PN actually is.
 *
 * The HP mask reveals **PN length** as part of unmasking the
 * first byte, which is why both operations have to happen
 * together — the caller cannot peek the PN length before
 * removing HP from the first byte.
 */
internal class HeaderProtection(hpKey: ByteArray) {
    init { require(hpKey.size == 16) { "AES-128 HP key must be 16 bytes" } }

    private val ecbKey = SecretKeySpec(hpKey, "AES")

    /**
     * Apply header protection to a packet being sent.
     *
     * @param firstByte the **unprotected** first byte of the
     *   packet (with PN length already encoded in low 2 bits).
     * @param pnBytes the **unprotected** packet-number bytes
     *   (length 1-4). Caller has already truncated the PN.
     * @param sample 16 bytes of AEAD ciphertext taken from
     *   `pn_offset + 4` within the same packet. If the actual
     *   PN is shorter, the sample reaches into the ciphertext
     *   past the PN — this is intentional and required.
     * @param isLongHeader true for Initial/Handshake/0-RTT/Retry,
     *   false for 1-RTT.
     * @return `(protectedFirstByte, protectedPnBytes)` ready to
     *   be written to the wire in place of the unprotected
     *   values.
     */
    fun apply(
        firstByte: Byte,
        pnBytes: ByteArray,
        sample: ByteArray,
        isLongHeader: Boolean,
    ): Pair<Byte, ByteArray> {
        require(pnBytes.size in 1..4) { "PN length must be 1..4, got ${pnBytes.size}" }
        val mask = computeMask(sample)
        val firstByteMask = if (isLongHeader) mask[0].toInt() and 0x0F
                            else mask[0].toInt() and 0x1F
        val protectedFirst = (firstByte.toInt() xor firstByteMask).toByte()
        val protectedPn = ByteArray(pnBytes.size)
        for (i in pnBytes.indices) {
            protectedPn[i] = (pnBytes[i].toInt() xor mask[1 + i].toInt()).toByte()
        }
        return protectedFirst to protectedPn
    }

    /**
     * Remove header protection from a received packet.
     *
     * The receiver doesn't know the PN length before removing HP
     * (it's in the protected low 2 bits of the first byte), so
     * the caller passes the **maximum** PN candidate region:
     * 4 bytes starting at `pn_offset`. After removing the first
     * byte's protection, we read the PN length and decode the
     * appropriate number of bytes from the masked region.
     *
     * @param firstByte the **protected** first byte as received.
     * @param encryptedPnRegion exactly 4 bytes starting at the
     *   packet's PN offset (i.e., raw bytes that may contain
     *   1, 2, 3, or 4 PN bytes followed by ciphertext bytes —
     *   the caller passes the maximum, we read only what we need).
     * @param sample 16 bytes starting at `pn_offset + 4` (i.e.,
     *   just past the maximum-PN region).
     * @param isLongHeader true for Initial/Handshake/0-RTT/Retry,
     *   false for 1-RTT.
     * @return `(unprotectedFirstByte, unprotectedPnBytes)` —
     *   the PN array's length is the actual PN length, derived
     *   from the unprotected first byte.
     */
    fun remove(
        firstByte: Byte,
        encryptedPnRegion: ByteArray,
        sample: ByteArray,
        isLongHeader: Boolean,
    ): Pair<Byte, ByteArray> {
        require(encryptedPnRegion.size == 4) {
            "must pass exactly 4 bytes for HP removal (caller supplies max PN candidate)"
        }
        val mask = computeMask(sample)
        val firstByteMask = if (isLongHeader) mask[0].toInt() and 0x0F
                            else mask[0].toInt() and 0x1F
        val unprotectedFirst = (firstByte.toInt() xor firstByteMask).toByte()
        val pnLength = (unprotectedFirst.toInt() and 0x03) + 1
        val unprotectedPn = ByteArray(pnLength)
        for (i in 0 until pnLength) {
            unprotectedPn[i] = (encryptedPnRegion[i].toInt() xor mask[1 + i].toInt()).toByte()
        }
        return unprotectedFirst to unprotectedPn
    }

    /**
     * Compute the 5-byte HP mask from a 16-byte ciphertext
     * sample. AES-128-ECB encrypts the sample; we keep the
     * first 5 bytes (1 for the first-byte mask, 4 for the
     * maximum-length PN mask).
     */
    private fun computeMask(sample: ByteArray): ByteArray {
        require(sample.size == 16) { "HP sample must be 16 bytes, got ${sample.size}" }
        val cipher = Cipher.getInstance("AES/ECB/NoPadding").apply {
            init(Cipher.ENCRYPT_MODE, ecbKey)
        }
        val out = cipher.doFinal(sample)
        // We only need 5 bytes; copy them so the caller can't
        // accidentally read into the rest of the mask (which is
        // valid AES output and would be a key-leak if exposed).
        return out.copyOfRange(0, 5)
    }
}
